import React, { useEffect } from "react";
import useDispatchFunc from "../hooks/useDispatchFunc";

import invoiceLogo from "./invoiceLogo.png";

const Invoice = () => {
  const [dispatch] = useDispatchFunc();

  useEffect(() => {
    dispatch({ type: "invoiceView" });
    return () => {
      dispatch({ type: "invoiceView" });
    };
  }, [dispatch]);

  return (
    <>
      <div className="bg-dark">
        <div>
          <div
            className="bg-white mx-auto"
            style={{ maxHeight: "297mm", maxWidth: "210mm" }}
          >
            {/* here comes everything */}
            <div className="container p-5 ">
              <div className="">
                {/* here logo and header */}
                <div className="d-flex justify-content-between align-items-center mb-5">
                  <div style={{ height: "100px", width: "auto" }}>
                    <img
                      src={invoiceLogo}
                      alt="LOGO"
                      height="100%"
                      width="100%"
                    />
                  </div>
                  <div className="lead"> TAX INVOICE / BILL / TAB </div>
                </div>
                {/* soldBy and ClientName */}
                <div className="d-flex justify-content-between mb-5">
                  <div className="d-flex flex-column">
                    <div className="fw-bold"> Sold By :</div>
                    <div className="d-flex flex-column">
                      <div>Nic Importers Inc</div>
                    </div>
                  </div>
                  <div className="d-flex flex-column align-items-end">
                    <div className="fw-bold">Shipped To :</div>
                    <div className="">
                      <div className="d-flex flex-column align-items-end">
                        <div>Customer1</div>
                        <div>Customer1@gmail.com</div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* here invoice no and date */}
                <div className="d-flex justify-content-between mb-5">
                  <div className="d-flex flex-column">
                    <div className="fw-bold">Invoice No :</div>
                    <div className="ms-1">2021-434</div>
                  </div>
                  <div className="d-flex flex-column">
                    <div className="fw-bold">Invoice Date :</div>
                    <div className="ms-1">
                      {new Date().toLocaleDateString()}
                    </div>
                  </div>
                </div>
                {/* here table */}
                <div>
                  <table className="table mb-5" style={{ lineHeight: "70px" }}>
                    <thead>
                      <tr className="">
                        <th>S.No</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Tax</th>
                        <th>Tax Amt</th>
                        <th>Total</th>
                      </tr>
                    </thead>
                    <tbody className="">
                      <tr className="">
                        <td>1.</td>
                        <td>
                          <div className="text-wrap text-break">
                            {" "}
                            Graphics Card RTX 2070 Super
                          </div>
                        </td>
                        <td>50000.00</td>
                        <td>12%</td>
                        <td>{((12 / 100) * 50000).toFixed(2)}</td>
                        <td>{((112 / 100) * 50000).toFixed(2)}</td>
                      </tr>
                      {/* here total Amount */}
                      <tr className="my-5 py-5">
                        <td colSpan="4" className="fw-bold">
                          Total Amount
                        </td>
                        <td>₹{((12 / 100) * 50000).toFixed(2)}</td>
                        <td>₹{((112 / 100) * 50000).toFixed(2)}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                {/* here employee name who generated invoice */}
                <div className="mb-5">
                  <div className=" d-flex flex-column ">
                    <div>Generated By : </div>
                    <div className="text-muted ms-2">
                      {" "}
                      Karthee (role if possible)
                    </div>
                  </div>
                </div>
                {/* here signature */}
                <div className="d-flex justify-content-end me-5 mb-5 ">
                  <div className="d-flex flex-column">
                    <div className=" p-2 mb-1 text-center lead">
                      Nic Importers Inc
                    </div>
                    <div className="fw-bold  border-top">
                      Authorized Signature
                    </div>
                  </div>
                </div>
                {/* here note */}
                <div className="mb-5 position-absolute">
                  <div className="text-muted fw-lighter fst-italic">
                    Payment due in 90 days from invoice date
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Invoice;
