import React from "react";

const InvoiceFinalAmt = () => {
  return (
    <>
      {/* here employee name who generated invoice & final amount*/}
      <div className="mb-4 d-flex justify-content-between">
        <div className=" d-flex flex-column ">
          <div>Generated By : </div>
          <div className="text-muted ms-2"> Karthee (role if possible)</div>
        </div>
        <div className=" d-flex flex-column ">
          <div>Final Amount:</div>
          <div className=" fw-bold">
            ₹ {((112 / 100) * 50000 * 2).toFixed(2)}
          </div>
        </div>
      </div>
    </>
  );
};

export default InvoiceFinalAmt;
